Algoritmo "Categoria_Do_Nadador"
// Autor(a)    : Tiago Lima
// Data atual  : 28/09/2017
Var
  Idade : Inteiro
Inicio
   Escreva ("Qual a idade ")
   Leia (Idade)
   escolha (Idade)
   Caso 0 ate 4
   Escreval ("Opção Invalida")
   Caso 5 ate 7
   Escreval ("Infantil A")
   Caso 8 ate 10
   Escreval ("Infantil B")
   Caso 11 ate 13
   Escreval ("Juvenil A")
   Caso 14 ate 17
   Escreval ("Juvenil B")
   Caso 18 ate 100000
   Escreval ("Senior " )
Fimescolha

Fimalgoritmo